/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahalalabirintusa;

import java.awt.Color;
import javax.swing.JTextArea;

/**
 *
 * @author Lenovo
 */
public class HalalLabirintusa extends javax.swing.JFrame {
    int erem=25;
    int szamlalo1=1;
    int szamlalo2=0;
    int eletero=10;
    String oldal1= "Miután öt percet haladtál lassan az alagútban, egy kőasztalhoz érsz, "
                + "amely a bal oldali fal mellett áll. Hat doboz van rajta, egyikükre a te neved festették."
                + " Ha kiakarod nyitni a dobozt, lapozz a 270-re. Ha inkább tovább haladsz észak felé, lapozz a 66-ra.";
    String oldal66="Néhány perc gyaloglás után egy elágazáshoz érsz az alagútban. "
                + "Egy, a falra festett fehér nyíl nyugatfelé mutat. A földön nedves lábnyomok jelzik, merre haladtak az előtted járók. Nehéz biztosan megmondani, de úgy tűnik, hogy három közülük a nyíl irányába halad, míg egyikük úgy döntött, hogy keletnek megy. "
                + "Ha nyugat felé kívánsz menni, lapozz a 293-ra. Ha keletnek, lapozz a 56-re.";
    String oldal56= "Látod, hogy az akadály egy széles, barna, sziklaszerű tárgy. Megérinted, és meglepve tapasztalod, hogy lágy, szivacsszerű."
            + " Ha át szeretnél mászni rajta, lapozz a 373-ra."
            + " Ha ketté akarod vágni a kardoddal, lapozz a 215-re.";
    String oldal137= "Ahogy végigmész az alagúton, csodálkozva látod, hogy egy jókora vasharang csüng alá a boltozatról.";
    String oldal215="Kardod könnyedén áthatol a spóragolyó vékonykülső burkán. Sűrű barna spórafelhő csap ki a golyóból, és körülvesz. Némelyik spóra a bőrödhöz tapad, és rettenetes viszketést okoz. Nagy daganatok nőnek az arcodon és karodon, és a bőröd mintha égne. "
            + "2 ÉLETERŐ pontot veszítesz. Vadul vakarózva átléped a leeresztett golyót, és keletnek veszed az utad.";
    String oldal270 ="A doboz teteje könnyedén nyílik. Benne két aranypénzt találsz, és egy üzenetet, amely egy kis pergamenen neked szól. Előbb zsebre vágod az aranyakat, aztán elolvasod az üzenetet: - „Jól tetted. Legalább volt annyi eszed, hogy megállj és elfogadd az ajándékot. Most azt tanácsolom neked, hogy keress és használj különféle tárgyakat, ha sikerrel akarsz áthaladni Halállabirintusomon.” "
            + "Azaláírás Szukumvit. Megjegyzed a tanácsot, apródarabokra téped a pergament, és tovább mészészak felé. Lapozz a 66-ra.";
    String oldal293="A három pár nedves lábnyomot követve az alagútnyugati elágazásában hamarosan egy újabb el-ágazáshoz érsz. Ha továbbmész nyugat felé a lábnyomokat követve, lapozz a 137-re."
            + " Ha inkább észak felé mész a harmadik pár lábnyom után, lapozz a 387-re.";
    String oldal373="Fölmászol a lágy sziklára, attól tartasz, hogy bár-melyik pillanatban elnyelhet. Nehéz átvergődni rajta, mert puha anyagában alig tudod a lábadat emelni, de végül átvergődsz rajta. Megkönnyebbülten érsz újra szilárd talajra, és fordulsz kelet felé.";
    String oldal387="Hallod, hogy elölről súlyos lépések közelednek. Egy széles, állatbőrökbe öltözött, kőbaltás, primitívlény lép elő. Ahogy meglát, morog, a földre köp, majd a kőbaltát felemelve közeledik, és mindennek kinéz, csak barátságosnak nem. Előhúzod kardodat, és felkészülsz, hogy megküzdj a Barlangi Emberrel.\n" +
"Barlangi Ember ÜGYESSÉG 7 ÉLETERŐ 7";
    
    
    public HalalLabirintusa() {
        initComponents();
        btnVarazslo.setOpaque(false);
        btnVarazslo.setBackground(new Color(0, 0, 0, 0));
        btnTorpe.setOpaque(false);
        btnTorpe.setBackground(new Color(0, 0, 0, 0));
        btnTunde.setOpaque(false);
        btnTunde.setBackground(new Color(0, 0, 0, 0));
        
        
        lblHatter.setVisible(false);
        pnlJatek.setVisible(false);
        pnlKarakterValasztas.setVisible(true);
        lblKarakterHatter.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlJatek = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaSzoveg = new javax.swing.JTextArea();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        lblKep = new javax.swing.JLabel();
        lblElet = new javax.swing.JLabel();
        lblEletMennyiseg = new javax.swing.JLabel();
        lblErme = new javax.swing.JLabel();
        lblErmeMennyiseg = new javax.swing.JLabel();
        lblCim = new javax.swing.JLabel();
        lblHatter = new javax.swing.JLabel();
        pnlKarakterValasztas = new javax.swing.JLayeredPane();
        btnTorpe = new javax.swing.JButton();
        btnVarazslo = new javax.swing.JButton();
        btnTunde = new javax.swing.JButton();
        lblKarakterCim = new javax.swing.JLabel();
        lblKepesseg = new javax.swing.JLabel();
        lblKarakterHatter = new javax.swing.JLabel();
        pnlKezdes = new javax.swing.JLayeredPane();
        lblElsoCim = new javax.swing.JLabel();
        btnKezdes = new javax.swing.JButton();
        lblHatterElso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halál Labirintus");
        setMaximumSize(new java.awt.Dimension(651, 453));
        setMinimumSize(new java.awt.Dimension(665, 488));
        setResizable(false);
        setSize(new java.awt.Dimension(651, 453));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        txtaSzoveg.setEditable(false);
        txtaSzoveg.setBackground(new java.awt.Color(91, 72, 41));
        txtaSzoveg.setColumns(20);
        txtaSzoveg.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtaSzoveg.setForeground(new java.awt.Color(239, 237, 193));
        txtaSzoveg.setLineWrap(true);
        txtaSzoveg.setRows(5);
        txtaSzoveg.setText("Egy versenyre nevezel, aminek a lényege, hogy át kell kelni a halállabirintuson. A labirintusban tárgyakat találhatsz és szörnyekkel kell harcoljál.");
        txtaSzoveg.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtaSzoveg);

        pnlJatek.add(jScrollPane1);
        jScrollPane1.setBounds(369, 71, 202, 241);

        btn1.setBackground(new java.awt.Color(91, 72, 41));
        btn1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(239, 237, 193));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        pnlJatek.add(btn1);
        btn1.setBounds(750, 330, 100, 53);

        btn2.setBackground(new java.awt.Color(91, 72, 41));
        btn2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btn2.setForeground(new java.awt.Color(239, 237, 193));
        btn2.setText("Kezdés");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        pnlJatek.add(btn2);
        btn2.setBounds(896, 330, 100, 53);

        lblKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/harcos3.png"))); // NOI18N
        pnlJatek.add(lblKep);
        lblKep.setBounds(111, 71, 185, 260);

        lblElet.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblElet.setText("Élet:");
        pnlJatek.add(lblElet);
        lblElet.setBounds(36, 360, 56, 33);

        lblEletMennyiseg.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblEletMennyiseg.setText("10");
        pnlJatek.add(lblEletMennyiseg);
        lblEletMennyiseg.setBounds(98, 360, 36, 33);

        lblErme.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblErme.setText("Érmék:");
        pnlJatek.add(lblErme);
        lblErme.setBounds(186, 360, 77, 33);

        lblErmeMennyiseg.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblErmeMennyiseg.setText("25");
        pnlJatek.add(lblErmeMennyiseg);
        lblErmeMennyiseg.setBounds(269, 360, 27, 33);

        lblCim.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblCim.setText("A HALÁL LABIRINTUSA");
        pnlJatek.add(lblCim);
        lblCim.setBounds(36, 26, 268, 33);

        lblHatter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/hatter4.png"))); // NOI18N
        pnlJatek.add(lblHatter);
        lblHatter.setBounds(-40, -10, 650, 470);

        getContentPane().add(pnlJatek);
        pnlJatek.setBounds(680, 10, 650, 450);

        btnTorpe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/harcos3.png"))); // NOI18N
        pnlKarakterValasztas.add(btnTorpe);
        btnTorpe.setBounds(400, 90, 240, 260);

        btnVarazslo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/varazslo.png"))); // NOI18N
        btnVarazslo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVarazsloMouseEntered(evt);
            }
        });
        pnlKarakterValasztas.add(btnVarazslo);
        btnVarazslo.setBounds(60, 80, 180, 270);

        btnTunde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/tunde1.png"))); // NOI18N
        pnlKarakterValasztas.add(btnTunde);
        btnTunde.setBounds(250, 90, 140, 260);

        lblKarakterCim.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblKarakterCim.setText("VÁLASSZ KARAKTERT!");
        pnlKarakterValasztas.add(lblKarakterCim);
        lblKarakterCim.setBounds(130, 30, 410, 50);
        pnlKarakterValasztas.add(lblKepesseg);
        lblKepesseg.setBounds(100, 360, 460, 60);

        lblKarakterHatter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/hatter4.png"))); // NOI18N
        pnlKarakterValasztas.add(lblKarakterHatter);
        lblKarakterHatter.setBounds(0, 0, 650, 450);

        getContentPane().add(pnlKarakterValasztas);
        pnlKarakterValasztas.setBounds(0, 0, 650, 0);

        lblElsoCim.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        lblElsoCim.setForeground(new java.awt.Color(249, 241, 213));
        lblElsoCim.setText("<html>\n<head>\n <h1 text align=\"center\">A HALÁL<br>LABIRINTUSA</h1>\n</head>\n</html>");
        pnlKezdes.add(lblElsoCim);
        lblElsoCim.setBounds(89, 59, 227, 140);

        btnKezdes.setBackground(new java.awt.Color(102, 0, 0));
        btnKezdes.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        btnKezdes.setText("<html>\n<head>\n <p color=\"white\">Induljon a kaland!</p>\n</head>\n</html>");
        btnKezdes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKezdesMouseClicked(evt);
            }
        });
        btnKezdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKezdesActionPerformed(evt);
            }
        });
        pnlKezdes.add(btnKezdes);
        btnKezdes.setBounds(98, 252, 162, 30);

        getContentPane().add(pnlKezdes);
        pnlKezdes.setBounds(10, 10, 630, 430);

        lblHatterElso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/csukott.png"))); // NOI18N
        getContentPane().add(lblHatterElso);
        lblHatterElso.setBounds(0, 0, 660, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        szamlalo2+=1;
            if (szamlalo2 == 1) {
                txtaSzoveg.setText(oldal1);
                btn1.setText("Kinyitom a dobozt 270");
                btn2.setText("Tovább észak felé 66");
            } else if (szamlalo2 == 2) {
                txtaSzoveg.setText(oldal66);
                btn1.setText("Nyugat felé 293");
                btn2.setText("Kelet felé 56");
            } else if (szamlalo2 == 3) {
                txtaSzoveg.setText(oldal56);
                btn1.setText("Átmászni 373");
                btn2.setText("Kettévágni 215");
            } else if (szamlalo2 == 4) {
                txtaSzoveg.setText(oldal215);
                btn1.setText("");
                btn2.setText("Tovább");
                eletero -= 2;
                lblEletMennyiseg.setText(""+eletero);
            } else if (szamlalo2 == 5) {
                txtaSzoveg.setText(oldal137);
                btn1.setText("");
                btn2.setText("Tovább");
            } else if (szamlalo2 == 6) {
                txtaSzoveg.setText(oldal387);
                btn1.setText("");
                btn2.setText("");
            }
//            } else if (szamlalo2 == 7) {
//                txtaSzoveg.setText(oldal215);
//                btn1.setText("Átmászni 373");
//                btn2.setText("Kettévágni 215");
//                //szamlalo2 += 1;
//            } else if (szamlalo2 == 8) {
//                txtaSzoveg.setText(oldal215);
//                btn1.setText("Átmászni 373");
//                btn2.setText("Kettévágni 215");
//                //szamlalo2 += 1;
//            } else {
//                txtaSzoveg.setText(oldal215);
//                btn1.setText("Átmászni 373");
//                btn2.setText("Kettévágni 215");
//                //szamlalo2 += 1;
    }//GEN-LAST:event_btn2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//    lblHatter.setVisible(false);
//    pnlJatek.setVisible(false);
//    pnlKarakterValasztas.setVisible(false);
//    lblKarakterHatter.setVisible(false);
    pnlKezdes.setVisible(true);
//        JTextArea txtaSzoveg = new JTextArea();
//    txtaSzoveg.setOpaque(false);
//    txtaSzoveg.setBackground(new Color(0, 0, 0, 0));
    }//GEN-LAST:event_formWindowOpened
        
    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        szamlalo1+=1;
            if (szamlalo1 == 1) {
                txtaSzoveg.setText(oldal1);
                btn1.setText("Kinyitom a dobozt 270");
                btn2.setText("Tovább észak felé 66");
            } else if (szamlalo1 == 2) {
                txtaSzoveg.setText(oldal270);
                btn1.setText("Tovább");
                btn2.setText("");
                erem+=10;
                lblErmeMennyiseg.setText(""+erem);
            } else if (szamlalo1 == 3) {
                txtaSzoveg.setText(oldal66);
                btn1.setText("Nyugat felé");
                btn2.setText("Kelet felé");
            } else if (szamlalo1 == 4) {
                txtaSzoveg.setText(oldal293);
                btn1.setText("Lábnyomokat követem");
                btn2.setText("");
            } else if (szamlalo1 == 5) {
                txtaSzoveg.setText(oldal137);
                btn1.setText("");
                btn2.setText("Tovább");
            } else if (szamlalo1 == 6) {
                txtaSzoveg.setText(oldal387);
                btn1.setText("");
                btn2.setText("");
            }
    }//GEN-LAST:event_btn1MouseClicked

    private void btnKezdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKezdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKezdesActionPerformed

    private void btnKezdesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKezdesMouseClicked
        lblKarakterHatter.setVisible(true);
        pnlKarakterValasztas.setVisible(true);
  
    }//GEN-LAST:event_btnKezdesMouseClicked

    private void btnVarazsloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVarazsloMouseEntered
    lblKepesseg.setText("Varázsló"+System.lineSeparator()+"Élet: 8"+System.lineSeparator()+"Érmék: 30"+System.lineSeparator()+"Képesség:Varázsereje van, úgyhogy félnek tőle a trollok.");
    }//GEN-LAST:event_btnVarazsloMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalalLabirintusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalalLabirintusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalalLabirintusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalalLabirintusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalalLabirintusa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btnKezdes;
    private javax.swing.JButton btnTorpe;
    private javax.swing.JButton btnTunde;
    private javax.swing.JButton btnVarazslo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCim;
    private javax.swing.JLabel lblElet;
    private javax.swing.JLabel lblEletMennyiseg;
    private javax.swing.JLabel lblElsoCim;
    private javax.swing.JLabel lblErme;
    private javax.swing.JLabel lblErmeMennyiseg;
    private javax.swing.JLabel lblHatter;
    private javax.swing.JLabel lblHatterElso;
    private javax.swing.JLabel lblKarakterCim;
    private javax.swing.JLabel lblKarakterHatter;
    private javax.swing.JLabel lblKep;
    private javax.swing.JLabel lblKepesseg;
    private javax.swing.JLayeredPane pnlJatek;
    private javax.swing.JLayeredPane pnlKarakterValasztas;
    private javax.swing.JLayeredPane pnlKezdes;
    private javax.swing.JTextArea txtaSzoveg;
    // End of variables declaration//GEN-END:variables
}
